name: Retweet SIMprove
on: 
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Run statsbot script
        env:
          SIMPROVEBOT_ACCESS_SECRET: ${{ secrets.SIMPROVEBOT_ACCESS_SECRET }}
          SIMPROVEBOT_ACCESS_TOKEN: ${{ secrets.SIMPROVEBOT_ACCESS_TOKEN }}
          SIMPROVEBOT_CONSUMER_KEY: ${{ secrets.SIMPROVEBOT_CONSUMER_KEY }}
          SIMPROVEBOT_CONSUMER_SECRET: ${{ secrets.SIMPROVEBOT_CONSUMER_SECRET }}
        run: |-
          Rscript -e "source('R/simprovebot.R')"
      - name: Commit results
        run: |
          git commit -m "Update data" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
